### ISSUE TITLE
Doesn't support M1 Mac

### ISSUE THREAD

**Issue by s50600822** [confluentinc/confluent-cli#139]
It seems the cli can't be installed on M1 Mac
```
curl -sL --http1.1 https://cnfl.io/cli | sh -s --  latest

confluentinc/cli crit platform darwin/arm64 is not supported.  Please contact Confluent support if you believe this is a mistake.
```

This is on

```
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro17,1
  Chip:	Apple M1
  Total Number of Cores:	8 (4 performance and 4 efficiency)
  Memory:	16 GB
  System Firmware Version:	6723.81.1
```

Not sure if meddling with
```
is_supported_platform() {
  platform=$1
  found=1
  case "$platform" in
    alpine/amd64) found=0 ;;
    linux/amd64) found=0 ;;
    linux/386) found=0 ;;
    darwin/amd64) found=0 ;;
    darwin/386) found=0 ;;
    windows/amd64) found=0 ;;
    windows/386) found=0 ;;
  esac
  case "$platform" in
    alpine/386) found=1 ;;
    darwin/386) found=1 ;;
  esac
  return $found
}
```
could bypass this, haven't tried myself.

**Comment by ewencp** [comment]
Bypassing it wouldn't help since it still needs the binary built for the target platform and we're only building and publishing the ones we currently support.

We're looking into how to handle arm64 support generally. As I'm sure you can imagine, supporting a new architecture across all components, including services, clients, CLIs, etc, requires careful consideration and testing. For the cli, it's probably not a huge effort (mostly build and install scripts adjusted to support it), but we need to look at support across the platform (e.g. a cli that runs on arm64 but doesn't have supported services probably isn't very useful).

It's possible working around this *might* work since M1s can run amd64 binaries, but that's not a tested path yet. (I don't personally have the hardware to test this unfortunately...)

**Comment by DABH** [comment]
@s50600822 @ewencp Closing this out since recent versions of the CLI do officially support arm64.  Thanks!

**Comment by prakashru** [comment]
Same issue here when I am trying to install on Mac Big Sur  (Version: 11.3.1) Apple Chip M1.

$confluent local services start 
confluentinc/cli crit platform darwin/arm64 is not supported.  Make sure this script is up-to-date and file request at https://github.com/confluentinc/cli/issues/new

Is there any solution for solving this issue?

**Comment by powlo** [comment]
~~This still seems to be an issue.~~ Hmm seems I needed the confluent platform installer, not just confluent cli. If you try to run `local` commands with just the cli then you get an error about CONFLUENT_HOME variable.

**Comment by fzhcary** [comment]
I am still getting this error when install confluent 7.2.1 from tar ball to Mac air. Why is this issue closed?

**Comment by soapycattt** [comment]
Has this issue been resolved yet?
