### ISSUE TITLE
Invalid connector class. Check the connector configuration file. -- More details needed

### ISSUE THREAD

**Issue by raj-bigdata** [confluentinc/confluent-cli#144]
{
	"name": "jdbc_source_postgresql_01",
	"config": {
			"connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
			"tasks.max": "1",
			"connection.url": "jdbc:postgresql://localhost:5432/postgres?sslmode=require",
			"connection.user": "kafka_user",
			"connection.password": "kafka_user",
			"table.whitelist": "users",
			"mode": "timestamp+incrementing",
			"timestamp.column.name": "created_dt",
			"incrementing.column.name": "id",
			"query": "select id, name, address from users",
			"table.type":"TABLE",
			"poll.interval.ms": "5000",
			"topic.prefix": "pg_source_topic"
		}
}

I am struggling to understand the error. When uploaded using control center it just says "Invalid connector class. Check the connector configuration file." but no other details are furnished, please help.

**Comment by ewencp** [comment]
This means that the `connector.class` setting references a class for the Connector which has not been loaded. This could mean it's not installed or that your Connect worker configuration is not setup to load it properly.

You can see the connectors that are being loaded in the Connect worker log during startup. Taking a look at what is being loaded (and what seems to be missing) might give a better idea of where the problem lies.

**Comment by DABH** [comment]
This does not appear to be a bug with the Confluent CLI, so because of that (and because this issue has been inactive), I think it's safe to close this issue.  Please feel free to re-open if you are encountering what seems like buggy behavior with the Confluent CLI.  Thanks!
